version: '3'
services:
  db:
    image: postgis/postgis:9.5-2.5-alpine
    environment:
    - POSTGRES_USER=ekylibre
    - POSTGRES_PASSWORD=alexandre
    ports:
    - 5432:5432
    networks:
    - default
  ekylibre:
    image: ekylibre
    build: .
    environment:
    - EKYLIBRE_DATABASE_HOST=db
    - EKYLIBRE_DATABASE_NAME=ekylibre
    - EKYLIBRE_DATABASE_PASSWORD=alexandre
    ports:
    - 3000:3000
    depends_on:
    - db
    networks:
    - default

networks:
  default:
    driver: bridge

